### ISSUE TITLE
secret core release blockers

### ISSUE THREAD

**Issue by tbg** [tbg/cockroach#163]
(shhhh)
for now I'd lean towards adding items liberally and deciding that they're not release blockers later.

- [ ] https://github.com/cockroachdb/cockroach/issues/40257 @ajwerner
- [ ] https://github.com/cockroachdb/cockroach/issues/40213 @nvanbenschoten
- [ ] https://github.com/cockroachdb/cockroach/issues/12768 @tbg
- [ ] https://github.com/cockroachdb/cockroach/issues/40207 @danhhz
- [ ] https://github.com/cockroachdb/cockroach/issues/37906 @danhhz
- [ ] https://github.com/cockroachdb/cockroach/pull/39796 @tbg
- [x] https://github.com/cockroachdb/cockroach/issues/40328 @nvanbenschoten
- [ ] https://github.com/cockroachdb/cockroach/issues/39460 @tbg
- [ ] https://github.com/cockroachdb/cockroach/issues/36431 touch all nodes on refresh @nvanbenschoten
- [ ] https://github.com/cockroachdb/cockroach/issues/38785 acceptance/bank/cluster-recovery

Maybe not blockers b/c not new or not core but still seem pretty bad:

- [ ] https://github.com/cockroachdb/cockroach/issues/40367 @tbg @danhhz
- [ ] can't add stores to existing node -> prevent this configuration/warn user
- [ ] cloud storage cdc sinks are marked as experimental but there's a known correctness problem that we don't know how to fix -- @danhhz
- [ ] https://github.com/cockroachdb/cockroach/issues/40412

**Comment by nvanbenschoten** [comment]
- [ ] https://github.com/cockroachdb/cockroach/issues/38785

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/40447
